# Generated by Django 6.1 on 2026-08-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_commit_pullrequestfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequestfile',
            name='patch',
            field=models.TextField(blank=True, null=True),
        ),
    ]
