# Generated by Django 6.1 on 2026-08-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_pullrequestfile_patch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_full_name', models.CharField(max_length=255)),
                ('pr_number', models.IntegerField()),
                ('review_summary', models.TextField()),
                ('raw_ai_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
