# Generated by Django 6.1 on 2026-08-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_pullrequestreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='commit_sha',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
