# Generated by Django 6.1 on 2026-08-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_commit_sha'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('commit_sha__isnull', False)), fields=('pull_request', 'commit_sha'), name='unique_review_per_pull_request_commit'),
        ),
    ]
